# Generated by Django 5.0.7 on 2024-07-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='descrtiption',
            field=models.TextField(default=''),
        ),
    ]
