# Generated by Django 5.0.7 on 2024-07-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0005_chaivarity_descrtiption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaivarity',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
