# Generated by Django 5.0.7 on 2024-07-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0007_certificate_chaireviw_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate',
            new_name='chai',
        ),
    ]
